networks:
  backend:

volumes:
  pgdata:
  appdata:
  csvdata:
  redisdata:

services:
  db:
    image: postgres:16
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - backend
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:7-alpine
    container_name: ${REDIS_CONTAINER_NAME}
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "${REDIS_PORT}:6379"

  php:
    build:
      context: ./services/php-web
    container_name: ${PHP_CONTAINER_NAME}
    environment:
      RUST_BASE: ${RUST_BASE}
      JWST_HOST: ${JWST_HOST}
      JWST_API_KEY: ${JWST_API_KEY}
      JWST_EMAIL: ${JWST_EMAIL}
      JWST_PROGRAM_ID: ${JWST_PROGRAM_ID}
      ASTRO_APP_ID: ${ASTRO_APP_ID}
      ASTRO_APP_SECRET: ${ASTRO_APP_SECRET}

      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}

      DB_CONNECTION: pgsql
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}

      CACHE_STORE: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
    depends_on:
      db:
        condition: service_healthy
      go_iss:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - appdata:/var/www/html
      - ./services/php-web/laravel-patches:/opt/laravel-patches:ro

  go_iss:
    build:
      context: ./services/go-iss
    container_name: ${GO_ISS_CONTAINER_NAME}
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

      NASA_API_URL: ${NASA_API_URL}
      NASA_API_KEY: ${NASA_API_KEY}

      JWST_HOST: ${JWST_HOST}
      JWST_API_KEY: ${JWST_API_KEY}
      JWST_EMAIL: ${JWST_EMAIL}
      JWST_PROGRAM_ID: ${JWST_PROGRAM_ID}

      ASTRO_APP_ID: ${ASTRO_APP_ID}
      ASTRO_APP_SECRET: ${ASTRO_APP_SECRET}

      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}

      DB_CONNECTION: pgsql
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "${GO_ISS_PORT}:3000"

  nginx:
    image: nginx:1.27-alpine
    container_name: ${NGINX_CONTAINER_NAME}
    depends_on:
      - php
    volumes:
      - appdata:/var/www/html:ro
      - ./services/php-web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
    ports:
      - "${NGINX_PORT}:80"

  go_reporter:
    build:
      context: ./services/go-csv
    container_name: ${GO_REPORTER_CONTAINER_NAME}
    environment:
      CSV_OUT_DIR: /data/csv
      PGHOST: ${POSTGRES_HOST}
      PGPORT: "${POSTGRES_PORT}"
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}

      CRON_SCHEDULE: ${CRON_SCHEDULE}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - csvdata:/data/csv
    networks:
      - backend

  queue_worker:
    build:
      context: ./services/php-web
    container_name: ${QUEUE_WORKER_CONTAINER_NAME}
    restart: always
    command: php artisan queue:work redis --tries=3 --timeout=90
    environment:
      APP_ENV: ${APP_ENV}

      DB_CONNECTION: pgsql
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}

      JWST_HOST: ${JWST_HOST}
      JWST_API_KEY: ${JWST_API_KEY}
      JWST_EMAIL: ${JWST_EMAIL}
      JWST_PROGRAM_ID: ${JWST_PROGRAM_ID}

      ASTRO_APP_ID: ${ASTRO_APP_ID}
      ASTRO_APP_SECRET: ${ASTRO_APP_SECRET}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - appdata:/var/www/html
    networks:
      - backend