networks:
  backend:

volumes:
  pgdata:
  appdata:
  csvdata:
  redisdata:

services:
  db:
    image: postgres:16
    container_name: iss_db
    environment:
      POSTGRES_DB: monolith
      POSTGRES_USER: monouser
      POSTGRES_PASSWORD: monopass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monouser -d monolith"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - backend
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: iss_redis
    command: redis-server --appendonly yes --requirepass monoredispass
    volumes:
      - redisdata:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "monoredispass", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"

  php:
    build:
      context: ./services/php-web
    container_name: php_web
    environment:
      RUST_BASE: http://go_iss:3000
      JWST_HOST: https://api.jwstapi.com
      JWST_API_KEY: baa96cdf-4a82-45f1-b986-d10a96826442
      JWST_EMAIL: burnfeniks@yandex.ru
      JWST_PROGRAM_ID: "2734"
      ASTRO_APP_ID: "745a5e07-70ae-49fc-8014-6a509551f829"
      ASTRO_APP_SECRET: "fe85a6503e3dd694a5d888effb336aefbbb5f54f348a134bd84126de5f69f536c5f05e75a55d395f41ae789b037bed48b7a505a690637acbf2108f5aefe3d934e0ab7b23bf469552d5eb6fc428f8ea981b02323cf3f6ec996ad7b6eab8312f786fd8c25eafc22cea532030c8dc3749c4"
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: monolith
      DB_USERNAME: monouser
      DB_PASSWORD: monopass
      REDIS_HOST: redis
      REDIS_PASSWORD: monoredispass
      REDIS_PORT: 6379
      CACHE_STORE: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
    depends_on:
      db:
        condition: service_healthy
      go_iss:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - appdata:/var/www/html
      - ./services/php-web/laravel-patches:/opt/laravel-patches:ro
  go_iss:
      build:
        context: ./services/go-iss
      container_name: go_iss
      environment:
        DATABASE_URL: postgres://monouser:monopass@db:5432/monolith
        NASA_API_URL: ${NASA_API_URL:-}
        NASA_API_KEY: ${NASA_API_KEY:-}
        JWST_HOST: https://api.jwstapi.com
        JWST_API_KEY: baa96cdf-4a82-45f1-b986-d10a96826442
        JWST_EMAIL: burnfeniks@yandex.ru
        JWST_PROGRAM_ID: "2734"
        ASTRO_APP_ID: ${ASTRO_APP_ID}
        ASTRO_APP_SECRET: ${ASTRO_APP_SECRET}
        APP_ENV: local
        APP_DEBUG: "true"
        APP_URL: http://localhost:8080
        DB_CONNECTION: pgsql
        DB_HOST: db
        DB_PORT: 5432
        DB_DATABASE: monolith
        DB_USERNAME: monouser
        DB_PASSWORD: monopass
      depends_on:
        db:
          condition: service_healthy
      networks:
        - backend
      ports:
        - "8081:3000"
  nginx:
    image: nginx:1.27-alpine
    container_name: web_nginx
    depends_on:
      - php
    volumes:
      - appdata:/var/www/html:ro
      - ./services/php-web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
    ports:
      - "8080:80"
  
  go_reporter:
    build:
      context: ./services/go-csv
    container_name: go_reporter
    environment:
      CSV_OUT_DIR: /data/csv
      PGHOST: db
      PGPORT: "5432"
      PGUSER: monouser
      PGPASSWORD: monopass
      PGDATABASE: monolith

      CRON_SCHEDULE: "*/5 * * * *"

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - csvdata:/data/csv
    networks:
      - backend

  queue_worker:
    build:
      context: ./services/php-web
    container_name: php_worker
    restart: always
    command: php artisan queue:work redis --tries=3 --timeout=90
    environment:
      APP_ENV: local
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: monolith
      DB_USERNAME: monouser
      DB_PASSWORD: monopass
      REDIS_HOST: redis
      REDIS_PASSWORD: monoredispass
      REDIS_PORT: 6379
      JWST_HOST: https://api.jwstapi.com
      JWST_API_KEY: baa96cdf-4a82-45f1-b986-d10a96826442
      JWST_EMAIL: burnfeniks@yandex.ru
      JWST_PROGRAM_ID: "2734"
      ASTRO_APP_ID: ${ASTRO_APP_ID}
      ASTRO_APP_SECRET: ${ASTRO_APP_SECRET}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - appdata:/var/www/html
    networks:
      - backend
